<?php
return [
    [
        'field' => 'jyomuin_cd',
        'title' => '乗務員コード',
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
        'class' => 'size-M',
        'formatter' => 'formatJyomuinCd'
    ],
    [
        'field' => 'kana',
        'title' => 'ヨミガナ',
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
        'class' => 'size-L',
    ],
    [
        'field' => 'jyomuin_nm',
        'title' => '名称',
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
        'class' => 'size-2L',
    ],
    [
        'field' => 'bumon_cd',
        'title' => '所属部門コード',
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
        'class' => 'size-M',
    ],
    [
        'field' => 'bumon_nm',
        'title' => '部門名',
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
        'class' => 'size-M',
    ],
    [
        'field' => 'mobile_tel',
        'title' => '携帯電話',
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
        'class' => 'size-M',
    ],
    [
        'field' => $f = 'mail',
        'title' => trans("attributes.m_jyomuin.{$f}"),
        'editable' => false,
        'visible' => true,
        'width' => 200,
        'suggestion' => false,
    ],
    [
        'field' => 'kyumin_flg',
        'title' => '休眠フラグ',
        'editable' => false,
        'visible' => true,
        'width' => '200',
        'suggestion' => false,
        'class' => 'size-M',
        'formatter' => 'formatKyuminFlg',
        'options' => configParam('options.m_jyomuin.kyumin_flg', [], 1)
    ],
];
