<?php 
return [
 
    [
        'field' => 'btn_copy',
        'title' => '',
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'displayBtnCopy',
    ],
    [
        'field' => 'btn_edit',
        'title' => '',
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'displayBtnEdit',
    ],
    [
        'field' => 'ninusi_cd',
        'title' => trans('attributes.m_soko_hinmei.ninusi_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'ninusi_nm',
        'title' => trans('attributes.m_soko_hinmei.ninusi_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'hinmei_cd',
        'title' => trans('attributes.m_soko_hinmei.hinmei_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'align' => 'right',
    ],
    [
        'field' => 'kana',
        'title' => trans('attributes.m_soko_hinmei.kana'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'hinmei_nm',
        'title' => trans('attributes.m_soko_hinmei.hinmei_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'kikaku',
        'title' => trans('attributes.m_soko_hinmei.kikaku'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'ondo',
        'title' => trans('attributes.m_soko_hinmei.ondo'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatOndo',
        'options' => configParam('options.m_soko_hinmei.ondo', [], 1)
    ],
    [
        'field' => 'zaiko_kbn',
        'title' => trans('attributes.m_soko_hinmei.zaiko_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatZaikoKbn',
        'options' => configParam('options.m_soko_hinmei.zaiko_kbn', [], 1)
    ],
    [
        'field' => 'case_cd',
        'title' => trans('attributes.m_soko_hinmei.case_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'case_nm',
        'title' => trans('attributes.m_soko_hinmei.case_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'irisu',
        'title' => trans('attributes.m_soko_hinmei.irisu'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
    ],
    [
        'field' => 'hasu_kiriage',
        'title' => trans('attributes.m_soko_hinmei.hasu_kiriage'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
    ],
    [
        'field' => 'bara_tani',
        'title' => trans('attributes.m_soko_hinmei.bara_tani'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'bara_tani_nm',
        'title' => trans('attributes.m_soko_hinmei.bara_tani_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'bara_tani_juryo',
        'title' => trans('attributes.m_soko_hinmei.bara_tani_juryo'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',

    ],
    [
        'field' => 'uke_tanka',
        'title' => trans('attributes.m_soko_hinmei.uke_tanka'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'seikyu_hinmei_cd',
        'title' => trans('attributes.m_soko_hinmei.seikyu_hinmei_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'seikyu_hinmei_nm',
        'title' => trans('attributes.m_soko_hinmei.seikyu_hinmei_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'keisan_kb',
        'title' => trans('attributes.m_soko_hinmei.keisan_kb'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatKeisanKb',
        'options' => configParam('options.m_soko_hinmei.keisan_kb', [], 1)
    ],
    [
        'field' => 'seikyu_keta',
        'title' => trans('attributes.m_soko_hinmei.seikyu_keta'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatSeikyuKeta',
        'options' => configParam('options.m_soko_hinmei.seikyu_keta', [], 1)
    ],
    [
        'field' => 'seikyu_bunbo',
        'title' => trans('attributes.m_soko_hinmei.seikyu_bunbo'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'nieki_nyuko_tanka',
        'title' => trans('attributes.m_soko_hinmei.nieki_nyuko_tanka'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'nieki_syuko_tanka',
        'title' => trans('attributes.m_soko_hinmei.nieki_syuko_tanka'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'hokanryo_kin',
        'title' => trans('attributes.m_soko_hinmei.hokanryo_kin'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'bumon_cd',
        'title' => trans('attributes.m_soko_hinmei.bumon_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'bumon_nm',
        'title' => trans('attributes.m_soko_hinmei.bumon_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
   
    [
        'field' => 'kyumin_flg',
        'title' => trans('attributes.m_soko_hinmei.kyumin_flg'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatKyuminFlg',
        'options' => configParam('options.m_soko_hinmei.kyumin_flg', [], 1)
    ],
    [
        'field' => 'add_user_cd',
        'title' => '登録者',
        'editable' => false,
        'visible' => false,
        'suggestion' => false
    ],
    [
        'field' => 'add_dt',
        'title' => '登録日',
        'editable' => false,
        'visible' => false,
        'suggestion' => false
    ],
    [
        'field' => 'upd_user_cd',
        'title' => '更新者',
        'editable' => false,
        'visible' => false,
        'suggestion' => false
    ],
    [
        'field' => 'upd_dt',
        'title' => '更新日',
        'editable' => false,
        'visible' => false,
        'suggestion' => false
    ],

];