<?php 
return [
 
    [
        'field' => 'yousya_cd',
        'title' => trans('attributes.m_yousya.yousya_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => "formatYousyaCd",
    ],
    [
        'field' => 'kana',
        'title' => trans('attributes.m_yousya.kana'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'yousya1_nm',
        'title' => trans('attributes.m_yousya.yousya1_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'yousya2_nm',
        'title' => trans('attributes.m_yousya.yousya2_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'yousya_ryaku_nm',
        'title' => trans('attributes.m_yousya.yousya_ryaku_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'bumon_cd',
        'title' => trans('attributes.m_yousya.bumon_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'bumon_nm',
        'title' => trans('attributes.m_yousya.bumon_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'yubin_no',
        'title' => trans('attributes.m_yousya.yubin_no'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'jyusyo1_nm',
        'title' => trans('attributes.m_yousya.jyusyo1_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'jyusyo2_nm',
        'title' => trans('attributes.m_yousya.jyusyo2_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],

    [
        'field' => 'tel',
        'title' => trans('attributes.m_yousya.tel'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'fax',
        'title' => trans('attributes.m_yousya.fax'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'siharai_kbn',
        'title' => trans('attributes.m_yousya.siharai_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatSiharaiKbn',
        'options' => configParam('options.m_yousya.siharai_kbn', [], 1)
    ],
    [
        'field' => 'siharai_cd',
        'title' => trans('attributes.m_yousya.siharai_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'siharai_nm',
        'title' => trans('attributes.m_yousya.siharai_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
  
    [
        'field' => 'yousya_ritu',
        'title' => trans('attributes.m_yousya.yousya_ritu'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'siharai_umu_kbn',
        'title' => trans('attributes.m_yousya.siharai_umu_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatSiharaiUmuKbn',
        'options' => configParam('options.m_yousya.siharai_umu_kbn', [], 1)
    ],
    [
        'field' => 'simebi1',
        'title' => trans('attributes.m_yousya.simebi1'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'simebi2',
        'title' => trans('attributes.m_yousya.simebi2'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'simebi3',
        'title' => trans('attributes.m_yousya.simebi3'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'mikakutei_seigyo_kbn',
        'title' => trans('attributes.m_yousya.mikakutei_seigyo_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatMikakuteiSeigyoKbn',
        'options' => configParam('options.m_yousya.mikakutei_seigyo_kbn', [], 1)
    ],
    [
        'field' => 'kin_hasu_kbn',
        'title' => trans('attributes.m_yousya.kin_hasu_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatKinHasuKbn',
        'options' => configParam('options.m_yousya.kin_hasu_kbn', [], 1)
    ],
    [
        'field' => 'kin_hasu_tani',
        'title' => trans('attributes.m_yousya.kin_hasu_tani'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatKinHasuTani',
        'options' => configParam('options.m_yousya.kin_hasu_tani', [], 1)
    ],
    [
        'field' => 'zei_keisan_kbn',
        'title' => trans('attributes.m_yousya.zei_keisan_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatZeiKeisanKbn',
        'options' => configParam('options.m_yousya.zei_keisan_kbn', [], 1)
    ],
    [
        'field' => 'zei_hasu_kbn',
        'title' => trans('attributes.m_yousya.zei_hasu_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatZeiHasuKbn',
        'options' => configParam('options.m_yousya.zei_hasu_kbn', [], 1)
    ],
    [
        'field' => 'zei_hasu_tani',
        'title' => trans('attributes.m_yousya.zei_hasu_tani'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatZeiHasuTani',
        'options' => configParam('options.m_yousya.zei_hasu_tani', [], 1)
    ],
    [
        'field' => 'kaikake_saki_cd',
        'title' => trans('attributes.m_yousya.kaikake_saki_cd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'kaikake_saki_nm',
        'title' => trans('attributes.m_yousya.kaikake_saki_nm'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'siharai_nyuryoku_umu_kbn',
        'title' => trans('attributes.m_yousya.siharai_nyuryoku_umu_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatSiharaiNyuryokuUmuKbn',
        'options' => configParam('options.m_yousya.siharai_nyuryoku_umu_kbn', [], 1)
    ],
    [
        'field' => 'siharai1_dd',
        'title' => trans('attributes.m_yousya.siharai1_dd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'siharai2_dd',
        'title' => trans('attributes.m_yousya.siharai2_dd'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'halign' => 'center',
        'align' => 'right',
        'formatter' => 'formatNumber',
    ],
    [
        'field' => 'comennt',
        'title' => trans('attributes.m_yousya.comennt'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'kensaku_kbn',
        'title' => trans('attributes.m_yousya.kensaku_kbn'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatKensakuKbn',
        'options' => configParam('options.m_yousya.kensaku_kbn', [], 1)
    ],
    [
        'field' => 'mail',
        'title' => trans('attributes.m_yousya.mail'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'haisya_biko',
        'title' => trans('attributes.m_yousya.haisya_biko'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'biko',
        'title' => trans('attributes.m_yousya.biko'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
    ],
    [
        'field' => 'kyumin_flg',
        'title' => trans('attributes.m_yousya.kyumin_flg'),
        'editable' => false,
        'visible' => true,
        'suggestion' => false,
        'formatter' => 'formatKyuminFlg',
        'options' => configParam('options.m_yousya.kyumin_flg', [], 1)
    ],
    [
        'field' => 'add_user_cd',
        'title' => '登録者',
        'editable' => false,
        'visible' => false,
        'suggestion' => false,
    ],
    [
        'field' => 'add_dt',
        'title' => '登録日',
        'editable' => false,
        'visible' => false,
        'suggestion' => false,
    ],
    [
        'field' => 'upd_user_cd',
        'title' => '更新者',
        'editable' => false,
        'visible' => false,
        'suggestion' => false,
    ],
    [
        'field' => 'upd_dt',
        'title' => '更新日',
        'editable' => false,
        'visible' => false,
        'suggestion' => false,
    ],

];