<?php


namespace App\Http\Requests;


use Illuminate\Validation\Rule;

class UriageNouhinsyoRequest extends UriageRequest
{
    function rules(): array
    {
        switch ($this->route()->getName()) {
            case 'uriage.nouhinsyo.filterValidate':
                return [
                    'exp.bumon_cd_from' => 'nullable|string|max:4|exists:m_bumon,bumon_cd',
                    'exp.bumon_nm_from' => 'nullable|string|max:20',
                    'exp.bumon_cd_to' => 'nullable|string|max:4|exists:m_bumon,bumon_cd',
                    'exp.bumon_nm_to' => 'nullable|string|max:20',

                    'exp.syuka_dt_from' => 'nullable|date_format:Y/m/d',
                    'exp.syuka_dt_to' => 'nullable|date_format:Y/m/d',

                    'exp.ninusi_cd_from' => 'nullable|string|max:10|exists:m_ninusi,ninusi_cd',
                    'exp.ninusi_nm_from' => 'nullable|string|max:40',
                    'exp.ninusi_cd_to' => 'nullable|string|max:10|exists:m_ninusi,ninusi_cd',
                    'exp.ninusi_bm_to' => 'nullable|string|max:40',

                    'exp.jyutyu_kbn_from' => $ruleJyutyuKbn = [
                        'nullable',
                        'max:4',
                        Rule::exists('m_meisyo', 'meisyo_cd')->where(function ($query) {
                            return $query->where('meisyo_kbn', configParam('MEISYO_KBN_JYUTYU'));
                        }),
                    ],
                    'exp.jyutyu_kbn_nm_from' => 'nullable|string|max:20',
                    'exp.jyutyu_kbn_to' => $ruleJyutyuKbn,
                    'exp.jyutyu_kbn_nm_to' => 'nullable|string|max:20',

                    'exp.uriage_den_no_from' => $ruleDenNo = 'nullable|integer|min:' . configParam('DB_INT_SIGNED_MIN')
                        . '|max:' . configParam('DB_INT_SIGNED_MAX'),
                    'exp.uriage_den_no_to' => $ruleDenNo,
                ];
        }
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributes(): array
    {
        return [
            'exp.bumon_cd_from' => '配車部門CD（開始）',
            'exp.bumon_cd_to' => '配車部門CD（終了）',
            'exp.syuka_dt_from' => '集荷日From',
            'exp.syuka_dt_to' => '集荷日To',
            'exp.ninusi_cd_from' => '荷主CD（開始）',
            'exp.ninusi_cd_to' => '荷主CD（終了）',
            'exp.jyutyu_kbn_from' => '受注区分CD（開始）',
            'exp.jyutyu_kbn_to' =>'受注区分CD（終了）',
            'exp.uriage_den_no_from' =>'売上番号From',
            'exp.uriage_den_no_to' =>'売上番号To',
        ];
    }

    public function messages(): array
    {
        return [
            'exp.bumon_cd_from.exists' => trans('messages.E0005', ['table' => '部門マスタ']),
            'exp.bumon_cd_to.exists' => trans('messages.E0005', ['table' => '部門マスタ']),
            'exp.*.date_format' => trans('messages.E0007'),
            'exp.ninusi_cd_from.exists' => trans('messages.E0005', ['table' => '荷主マスタ']),
            'exp.ninusi_cd_to.exists' => trans('messages.E0005', ['table' => '荷主マスタ']),
            'exp.jyutyu_kbn_from.exists' => trans('messages.E0005', ['table' => '名称マスタ']),
            'exp.jyutyu_kbn_to.exists' => trans('messages.E0005', ['table' => '名称マスタ']),
        ];
    }
}
