<?php

namespace App\Http\Controllers\HanyouKensaku\Kinou;

use App\Helpers\Excel\XlsRyoshusho;
use App\Http\Controllers\HanyouKensaku\HanyouKensakuController;
use App\Http\Repositories\HanyouKensaku\RyoshushoRepository;
use Illuminate\Http\Request;

class RyoshushoController extends HanyouKensakuController
{
    public function __construct(RyoshushoRepository $repository)
    {
        $this->dataRepository = $repository;
    }

    public function exportExcelDataTable(Request $request)
    {
        $mode = $request->mode;
        $this->fileName = "ryoshusho_{$mode}.xlsx";
        $this->configExcel = require(app_path("Helpers/Excel/config/hanyou_kensaku/ryoshusho_{$mode}.php"));
        $this->templatePath = app_path("Helpers/Excel/template/hanyou_kensaku/ryoshusho_{$mode}.xlsx");
        $this->exporter = new XlsRyoshusho();

        return parent::exportExcelDataTable($request); // TODO: Change the autogenerated stub
    }
}
