<?php
return [
    'bumon_cd' => '部門コード',
    'bumon_nm' => '部門名',
    'ninusi_cd' => '荷主コード',
    'ninusi_ryaku_nm' => '荷主略称',
    'ninusi1_nm' => '荷主名１',
    'ninusi2_nm' => '荷主名２',
    'kisan_dt_from' => '開始日',
    'kisan_dt_to' => '終了日',
    'hinmei_cd' => '商品コード',
    'hinmei_nm' => '商品名',
    'kikaku' => '商品規格',
    'lot1' => 'ロット番号１',
    'lot2' => 'ロット番号２',
    'lot3' => 'ロット番号３',
    'tani_cd' => '単位コード',
    'tani_nm' => '単位名',
    'irisu' => '入数',
    'case_cd' => 'ケース単位コード',
    'case_nm' => 'ケース単位名',
    'zaiko_case_su' => '繰越ケース',
    'zaiko_hasu' => '繰越端数',
    'zaiko_su' => '繰越総数',
    'zaiko_jyuryo' => '繰越重量',
    'in_case_su' => '入庫ケース',
    'in_hasu' => '入庫端数',
    'in_su' => '入庫総数',
    'in_jyuryo' => '入庫重量',
    'out_case_su' => '出庫ケース',
    'out_hasu' => '出庫端数',
    'out_su' => '出庫総数',
    'out_jyuryo' => '出庫重量',
    'zankou_case_su' => '在庫ケース',
    'zankou_hasu' => '在庫端数',
    'zankou_su' => '在庫総数',
    'zankou_jyuryo' => '在庫重量',
];