<?php
return [
    'seikyu_cd' => '集約請求先コード',
    'seikyu_ninusi_ryaku_nm' => '請求荷主略名',
    'seikyu_ninusi1_nm' => '請求荷主名１',
    'seikyu_ninusi2_nm' => '請求荷主名２',
    'ninusi_cd' => '荷主コード',
    'ninusi_ryaku_nm' => '荷主略名',
    'ninusi1_nm' => '荷主名１',
    'ninusi2_nm' => '荷主名２',
    'kisei_kbn' => '期制区分',
    '形式' => '形式',
    '請求額計算区分' => '請求額計算区分',
    '請求品名コード' => '請求品名コード',
    '請求品名' => '請求品名',
    'hinmei_cd' => '商品コード',
    'hinmei_nm' => '商品名',
    'kikaku' => '商品規格',
    'irisu' => '入数',

    'ki1_kurikosi_su' => '１期：繰越・数量',
    'ki1_kurikosi_case_su' => '１期：繰越・ケース数',
    'ki1_kurikosi_hasu' => '１期：繰越・端数',
    'ki1_kurikosi_juryo' => '１期：繰越・重量',
    'ki1_nyuko_su' => '１期：入庫・数量',
    'ki1_nyuko_case_su' => '１期：入庫・ケース数',
    'ki1_nyuko_hasu' => '１期：入庫・端数',
    'ki1_nyuko_juryo' => '１期：入庫・重量',
    'ki1_syuko_su' => '１期：出庫・数量',
    'ki1_syuko_case_su' => '１期：出庫・ケース数',
    'ki1_syuko_hasu' => '１期：出庫・端数',
    'ki1_syuko_juryo' => '１期：出庫・重量',

    'ki2_kurikosi_su' => '２期：繰越・数量',
    'ki2_kurikosi_case_su' => '２期：繰越・ケース数',
    'ki2_kurikosi_hasu' => '２期：繰越・端数',
    'ki2_kurikosi_juryo' => '２期：繰越・重量',
    'ki2_nyuko_su' => '２期：入庫・数量',
    'ki2_nyuko_case_su' => '２期：入庫・ケース数',
    'ki2_nyuko_hasu' => '２期：入庫・端数',
    'ki2_nyuko_juryo' => '２期：入庫・重量',
    'ki2_syuko_su' => '２期：出庫・数量',
    'ki2_syuko_case_su' => '２期：出庫・ケース数',
    'ki2_syuko_hasu' => '２期：出庫・端数',
    'ki2_syuko_juryo' => '２期：出庫・重量',

    'ki3_kurikosi_su' => '３期：繰越・数量',
    'ki3_kurikosi_case_su' => '３期：繰越・ケース数',
    'ki3_kurikosi_hasu' => '３期：繰越・端数',
    'ki3_kurikosi_juryo' => '３期：繰越・重量',
    'ki3_nyuko_su' => '３期：入庫・数量',
    'ki3_nyuko_case_su' => '３期：入庫・ケース数',
    'ki3_nyuko_hasu' => '３期：入庫・端数',
    'ki3_nyuko_juryo' => '３期：入庫・重量',
    'ki3_syuko_su' => '３期：出庫・数量',
    'ki3_syuko_case_su' => '３期：出庫・ケース数',
    'ki3_syuko_hasu' => '３期：出庫・端数',
    'ki3_syuko_juryo' => '３期：出庫・重量',

    'touzan_su' => '当月：残・数量',
    'touzan_case_su' => '当月：残・ケース数',
    'touzan_hasu' => '当月：残・端数',
    'touzan_juryo' => '当月：残・重量',

    'seki_su' => '保管積数・数量',
    'seki_juryo' => '保管積数・重量',
    'tanka' => '保管単価',
    'hokan_kin' => '保管料',

    'nyuko_su' => '入庫荷役・数量',
    'nyuko_juryo' => '入庫荷役・重量',
    'nyuko_tanka' => '入庫荷役・単価',
    'nyuko_kin' => '入庫荷役料',

    'syuko_su' => '出庫荷役・数量',
    'syuko_juryo' => '出庫荷役・重量',
    'syuko_tanka' => '出庫荷役・単価',
    'syuko_kin' => '出庫荷役料',

    'total_kin' => '請求合計',
    'seikyu_sime_dt' => '締日',

    '会社名' => '会社名',
    '代表者名' => '代表者名',
    '宛先敬称' => '宛先敬称',
    '自社名印字区分' => '自社名印字区分',
    '倉庫請求書印字少数桁' => '倉庫請求書印字少数桁',
    '倉庫請求書印字分母' => '倉庫請求書印字分母',
];
