<?php 
    return [
        'kisan_dt' => '出庫日',
        'bumon_cd' => '部門コード',
        'bumon_nm' => '部門名',
        'soko_cd' => '倉庫コード',
        'soko_nm' => '倉庫名',
        'location' => 'ロケーション',
        'ninusi_cd' => '荷主コード',	
        'ninusi1_nm' => '荷主名',
        'hinmei_cd' => '商品コード',
        'hinmei_nm' => '商品名',
        'kikaku' => '商品規格',
        'lot1' => 'ロット番号１',	
        'lot2' => 'ロット番号２',
        'lot3' => 'ロット番号３',
        'case_su' => '出庫ケース',
        'hasu' => '出庫端数',
        'su' => '出庫総数',
        'irisu' => '入数',
        'case_cd' => 'ケース単位コード',
        'case_nm' => 'ケース単位名',
        'tani_cd' => '単位コード',
        'tani_nm' => '単位名',
        't_zaiko__case_su' => '在庫ケース',
        't_zaiko__hasu' => '在庫端数',
        't_zaiko__su' => '在庫総数',
    ];