<?php 
    return [
        'kisan_dt' => '出庫日', 
        'bumon_cd' => '部門コード', 
        'bumon_nm' => '部門名',
        'syaban' => '車番',
        'jyomuin_cd' => '乗務員コード',
        'jyomuin_nm' => '乗務員名',
        'yousya_cd' => '傭車先コード', 
        'yousya_ryaku_nm' => '傭車先名',
        'hachaku_cd' => '荷届け先コード', 
        'todokesaki_nm' => '荷届け先名', 
        'ninusi_cd' => '荷主コード', 
        'ninusi1_nm' => '荷主名',
        'hinmei_cd' => '商品コード', 
        'hinmei_nm' => '商品名', 
        'kikaku' => '商品規格', 
        'lot1' => 'ロット番号１', 
        'lot2' => 'ロット番号２', 
        'lot3' => 'ロット番号３', 
        'case_su' => 'ケース', 
        'hasu' => '端数', 
        'su' => '総数', 
        'irisu' => '入数', 
        'case_cd' => 'ケース単位コード', 
        'case_nm' => 'ケース単位名',
        'bara_tani' => '単位コード', 
        'bara_tani_nm' => '単位名',
        'checkbox' => 'チェック欄',
    ];