<?php
return [
    'seikyu_sime_dt' => '締日',
    'ninusi_cd' => '荷主コード',
    'ninusi1_nm' => '荷主名',
    'zenkai_seikyu_kin' => '前回請求額',
    'genkin_kin' => '入金・現金',
    'furikomi_kin' => '入金・振込',
    'furikomi_tesuryo_kin' => '入金・振込手数料',
    'tegata_kin' => '入金・手形',
    'sousai_kin' => '入金・相殺',
    'nebiki_kin' => '入金・値引',
    'sonota_nyu_kin' => '入金・その他',
    'kjrikosi_kin' => '繰越額',
    'kazei_unchin_kin' => '基本運賃（課税）',
    'kazei_tyukei_kin' => '中継料（課税）',
    'kazei_tukouryou_kin' => '通行料等（課税）',
    //'' => '',
    'kazei_niyakuryo_kin' => '荷役料（課税）',
    //'' => '',
    'zei_kin' => '消費税',
    'hikazei_unchin_kin' => '基本運賃（非課税）',
    'hikazei_tyukei_kin' => '中継料（非課税）',
    'hikazei_tukouryo_kin' => '通行料等（非課税）',
    //'' => '',
    'hikazei_niyakuryo_kin' => '荷役料（非課税）',
    //'' => '',
    'konkai_torihiki_kin' => '今回取引額',
    'seikyu_kin' => '請求額',
    'mikakutei_kin' => '未確定金額',
    'kaisyu_yotei' => '回収予定',
    'zei_keisan_kbn' => '消費税計算区分',
    'mikakutei_su' => '未確定件数',
];
