<?php
return [
    'dt' => '日付',
    'bumon_cd' => '部門コード',
    'bumon_nm' => '部門名',
    'syaban' => '車番',
    'unso_dt' => '運行開始日',
    'card_nm' => '登録番号',
    'yousya_cd_status' => '自傭区分',
    'yousya_cd' => '傭車先コード',
    'yousya_ryaku_nm' => '傭車先名',
    'jyomuin_cd' => '運転者コード',
    'jyomuin_nm' => '運転者名',
    'ninusi_cd' => '荷主コード',
    'ninusi_ryaku_nm' => '荷主名',
    'hatuti_cd' => '発地コード',
    'hatuti_nm' => '発地名',
    'syuka_dt' => '集荷日',
    'syuka_tm' => '集荷時刻',
    'syuka_tm_2' => '集荷時刻(数値)',
    'hachaku_cd' => '着地コード',
    'hachaku_nm' => '着地名',
    'haitatu_dt' => '配達日',
    'jikoku' => '配達時刻',
    'jikoku_2' => '配達時刻(数値)',
    'jikoku_status' => '配達時間指定区分',
    'tyuki' => '配達注記',
    'haitatu_jyusyo1' => '配達住所１',
    'haitatu_jyusyo2' => '配達住所２',
    'hachaku_nm_2' => '荷受人',
    'haitatu_tel' => '配達電話番号',
    'haitatu_fax' => '配達ＦＡＸ番号',
    'hinmei_cd' => '品名コード',
    'hinmei_nm' => '品名',
    'su' => '数量',
    'tani_cd' => '単位コード',
    'tani_nm' => '単位名',
    'yosya_tyukei_kin' => '傭車料',
    'biko_cd' => '備考コード',
    'biko' => '備考',
    'nipou_dt' => '日報日付',
    'uriage_den_no' => '売上番号',

   

    //'add_user_cd' => '登録者',
    //'add_dt' => '登録日',
    //'upd_user_cd' => '更新者',
    //'upd_dt' => '更新日',
];
