<?php 
    return [
        'bumon_cd'      => '部門コード',
        'bumon_nm'      => '部門名',
        'soko_cd'       => '倉庫コード',
        'soko_nm'       => '倉庫名',
        'current_date'  => '棚卸日',
        'location'      => 'ロケーション',
        'ninusi_cd'     => '荷主コード',
        'ninusi1_nm'    => '荷主名',
        'hinmei_cd'     => '商品コード',
        'hinmei_nm'     => '商品名',
        'kikaku'        => '商品規格',
        'lot1'          => 'ロット番号１',
        'lot2'          => 'ロット番号２',
        'lot3'          => 'ロット番号３',
        'case_su'       => '帳簿在庫ケース（Ａ）',
        'hasu'          => '帳簿在庫端数（Ａ）',
        'su'            => '帳簿在庫総数（Ａ）',
        'irisu'         => '入数',
        'case_cd'       => 'ケース単位コード',
        'case_nm'       => 'ケース単位名',
        'bara_tani'     => '単位コード',
        'bara_tani_nm'  => '単位名',
        'jittana_kesu'  => '実棚ケース（Ｂ）',
        'jittana_hasu'  => '実棚端数（Ｂ）',
        'jittana_sosu'  => '実棚総数（Ｂ）',
        'sai_kesu'      => '差異ケース（Ｂ－Ａ）',
        'sai_hasu'      => '差異端数（Ｂ－Ａ）',
        'sai_sosu'      => '差異総数（Ｂ－Ａ）',
    ];